export const CLASSES = {
  warrior: {
    id: 'warrior',
    name: 'KRIEGER',
    icon: '🛡️',
    tagline: 'Stark, langsam, unaufhaltsam',
    baseHp: 150,
    baseAtk: 20,
    baseDef: 15,
    baseEnergy: 100,
    special: 'Schildstoß: Blockt Schaden und gibt zurück. Timing ist alles.',
    specialName: 'SCHILDSTOSS',
    specialCost: 40,
    specialEffect: { type: 'block_counter', damage: 1.5, blockWindow: 400 },
  },
  mage: {
    id: 'mage',
    name: 'MAGIER',
    icon: '🔮',
    tagline: 'Glas-Kanone mit Flächenschaden',
    baseHp: 90,
    baseAtk: 28,
    baseDef: 5,
    baseEnergy: 120,
    special: 'Feuerball: Trifft alle Gegner im Raum. Kurze Ladezeit.',
    specialName: 'FEUERBALL',
    specialCost: 50,
    specialEffect: { type: 'aoe', damage: 2.0, castTime: 600 },
  },
  rogue: {
    id: 'rogue',
    name: 'SCHURKE',
    icon: '🗡️',
    tagline: 'Schnell, trickreich, gefährlich',
    baseHp: 110,
    baseAtk: 24,
    baseDef: 8,
    baseEnergy: 100,
    special: 'Dolchsturm: Zwei schnelle Treffer. Perfektes Ausweichen verdoppelt Schaden.',
    specialName: 'DOLCHSTURM',
    specialCost: 35,
    specialEffect: { type: 'double_strike', damage: 0.8, dodgeBonus: 2.0 },
  },
}
